### PR TITLE
Adds tekton pipelines 0.8.0 release.yaml

### PR DESCRIPTION
**Pull request by hrishin**
cc: @sthaha @chmouel @vdemeester

### CODE REVIEW

**Comment by chmouel** [comment]
is the ci stuck?

**Comment by hrishin** [comment]
@chmouel the [job configuration](https://github.com/openshift/release/pull/5590) for https://github.com/openshift/tektoncd-pipeline/tree/release-v0.8.0 is not yet merged. Hence it may not be able to trigger the job.

**Comment by chmouel** [comment]
/lgtm
/approve
/meow

Thanks 🙇🏽‍♂️

**Pull request merged**
