### PR TITLE
Add check to defaultsa

### PR DESCRIPTION
**Pull request by praveen4g0**
# Changes

* upstream/midstream tests verifies for default service account when user creates a namespace, by default it's hard coded [here](https://github.com/tektoncd/pipeline/blob/main/test/init_test.go#L147) to `default` 

* so if we install pipelines components via operator it sets `default-service-account` to `pipeline` in `config-defaults` config map!

* so it's safe to use this patch both in upstream/downstream as it actually waits for right service account before it actually executest the tests  
 

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
Thank you @praveen4g0 This is good for this release branch. 
COuld you raise this pr in upstream pipelines as well.

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Pull request merged**
