### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by chmouel**

### CODE REVIEW

**Comment by vdemeester** [comment]
@chmouel shouldn't we close this one and let the bot re-start new job (hopefully without 4.2)

**Comment by piyush-garg** [comment]
@vdemeester I think the jobs are already doing right thing, only the names are not modified, @pradeepitm12 has raised https://github.com/openshift/release/pull/7026 for this

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
