### PR TITLE
change master to main for upstream

### PR DESCRIPTION
**Pull request by pradeepitm12**

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by piyush-garg** [comment]
@pradeepitm12 These changes are reuired in master branch

And this script will run in Jenkins, not openshift ci

/hold

**Comment by pradeepitm12** [comment]
> And this script will run in Jenkins, not openshift ci
Thank You , will create a new pr

**Comment by pradeepitm12** [comment]
closing in favor of https://github.com/openshift/tektoncd-pipeline/pull/627

**Pull request closed without merging**
