### PR TITLE
Downstream release 0.4.0 CI setup

### PR DESCRIPTION
**Pull request by chmouel**
/cc @arilivigni @sthaha @vdemeester @hrishin

### CODE REVIEW

**Comment by chmouel** [comment]
yay CI has picked up stuff!

**Comment by chmouel** [comment]
oh! so we need to do this in `openshift/release` as well I guess

**Comment by vdemeester** [comment]
@chmouel yes.. sorry I forgot about that when `lgtm`ed it.. :sweat:

**Comment by chmouel** [comment]
/hold

no worries, i just pushed a change in there but will modify the release repo first so this got tested properly, will then pickup this commit and push it to `openshift/master`

**Pull request merged**
