### PR TITLE
Skip TestWorkspacePipelineRunDuplicateWorkspaceEntriesInvalid Test

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Add a skip for TestWorkspacePipelineRunDuplicateWorkspaceEntriesInvalid test as this is
consitently failing on OpenShift

This test is checks a webhook validatation, which is more like a webhook unit test.

Work on a permananet fix is being tracked here: https://issues.redhat.com/browse/SRVKP-1656

Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
/hold

until https://github.com/openshift/tektoncd-pipeline/pull/732 passes

**Review by vdemeester — APPROVED** [review]
/lgtm

**Comment by nikhil-thomas** [comment]
The skip made the ci go past the test in question. So let us merge this patch.

**Pull request merged**
