### PR TITLE
Remove extra space

### PR DESCRIPTION
**Pull request by piyush-garg**
This will fix the isue of extra space in controller
and webhook image name in release.yaml generated by script

Because of this yaml lint check is getting failed for
operator

### CODE REVIEW

**Comment by chmouel** [comment]
Feel free to remove the comment about GCSutil

**Comment by piyush-garg** [comment]
I added the support in master, but this is changing the 0.9.2 branch, gs-util will be available from 0.10.0 onwards

**Comment by chmouel** [comment]
was it merged to master too?

**Comment by piyush-garg** [comment]
Yeah it was merged to master few days back

**Pull request merged**
